name: health check

on:
    schedule:
        - cron: '0 20 * * *'

jobs:
    health-check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: health check
              uses: jtalk/url-health-check-action@v3
              with:
                url: https://bloglist-backendcb10.fly.dev/
                max-attempts: 3
                retry-delay: 10s
                
